debug: false
points_dir: ..\data\torus_sample\1600.ply
out_dir:  ..\data\torus_sample\1600\1600
smooth_lambda: 0.1
normal_beta: 1.0
volumn_dim: 100 
enable_constriants: true # sum(a_i) = 0, sum(a_i * x) + sum(b_i) = 0 
save_inputs: true
save_estimate_normal: true # save rbf normal lines 
save_visualization: true   # save normal lines
save_eigen_vec: false
use_scan_data: false
use_gradient: false # only should be used when input is scan image data 
surface_weight: 1.0  # not used 
graidents_dir: /home/jjxia/Documents/projects/VIPSS/data/torus/multisample_n50/noise_gradients.ply
use_confidence: false
data_id: 6007
data_dir: ../All_Elbow/contours_3/
pt_normal_folder: ../contour_points/contour_ptnormal_6/
pt_gradient_folder: ../contour_points/gradients_tangent_6/
pt_normal_file: contour_ptnormal_6.ply
pt_gradient_file: gradients_tangent_6.ply
